### PR TITLE
 Added a option "NoGlow" in metrics.ini.

### PR DESCRIPTION
**Pull request by xNihil0**
Added a option in metrics.ini to disable flash (or glow in other words) when playing with hidden or sudden mod. Added a under-construction country ranking.

### CODE REVIEW

**Comment by nico-abram** [comment]
Why is this changing DownloadManager? Seems good otherwise :+1: . I think you might have accidentally commited extra stuff on dlman.
Are you on discord? :P

**Comment by xNihil0** [comment]
removed changes in DLMAN as well
now it should be good to go

**Comment by nico-abram** [comment]
If you know how to, could you try to squash/combine the last 5 (The ones which are yours) commits into one? You can contact me on discord if you want help with it.

**Comment by xNihil0** [comment]
Sure. I squashed the latest commits into one. Please tell me if i did it wrong.

**Pull request merged**
