### PR TITLE
Match cursor updaterate to display refresh rate

### PR DESCRIPTION
**Pull request by Jolomann**
Minor tweak. Now possible thanks to https://github.com/etternagame/etterna/commit/4c5dec0687b368019b678bb3922fbeff23c2e050

### CODE REVIEW

**Comment by poco0317** [comment]
Is there a reason we dont do `self:SetUpdateFunctionInterval( 1 / DISPLAY:DISPLAY:GetDisplayRefreshRate() )` instead?

**Comment by Jolomann** [comment]
There isn't. I can change it to that if it's better

**Comment by poco0317** [comment]
The have the same end effect, but using SetUpdateFunctionInterval would force the update speed to only apply to those things relevant to the update function instead of all children.
Think of what holding Tab does to the game. Holding Tab multiplies all update rates by 4. Your code multiplies the update rate of the ActorFrame by the refresh rate.

**Comment by Jolomann** [comment]
Ah, might as well only update the function then

**Pull request merged**
