### PR TITLE
Refactor Gameplay, Replays, and Practice

### PR DESCRIPTION
**Pull request by poco0317**
Putting this up a little early to monitor progress and let people piss me off by commenting on my code before it's done

Handles #463 
(by extension handles #367 #461 #473 #474 #476 #491 #495 #496 #578 ~~#582~~ #583 #588 ~~#593~~ #595 ~~#599~~ #601 #616)
Handles #497 #444 #644

### CODE REVIEW

**Comment by poco0317** [comment]
- [ ] In some cases, the Autoplay/Sync overlay does not update if the status is changed outside of gameplay.

**Comment by poco0317** [comment]
As of this writing, replays are "fixed," at least with respect to the playback of them being scored incorrectly.
Time to move on to all the other issues.

**Comment by poco0317** [comment]
As of writing, Chart Preview & Practice Mode sync is fixed. The drawback of this is that seeking is slower for long files. It was written in a way so that this only affects preview and practice seeking. This does not affect sample music playing.
The worst "lag" caused by this seems to be around 1-2 seconds for a 10 minute long seek. This is about the same amount of time it takes for sample music to start playing in normal situations.
An additional plus to seeking being written in this nonblocking way is that scrolling with preview opened will cause less stutter (due to loading audio and seeking far).

**Comment by Kangaroux** [comment]
@poco0317 Is the bottleneck for seeking I/O related?

**Comment by poco0317** [comment]
The changes to seeking are only relevant to MP3 files (and the other types are still capable of it, I just didn't change anything). What I did was force it to use an algorithm which seeks perfectly well forward at a reasonable speed, but if it has to go backwards the track must be started from 0 before seeking. The bottleneck here is perhaps in I/O but also how fast the CPU can decode the audio file either from 0 or from the point you are at depending on if you were trying to seek forward or backward.

See this commit and the relevant functions within SetPosition to see more info:
https://github.com/etternagame/etterna/pull/606/commits/7f6148d5a93ea181bfa8de42f6cdef3e869c992d

**Comment by poco0317** [comment]
Currently working through new issues with Replay seeking and then Practice mode can be worked on.

**Comment by poco0317** [comment]
Known issues that may not be fixed:
- Particularly unique files have sometimes unwatchable replays. One example is 1h54m JS, which uses an audio file that is literally empty. This breaks timestamp seeking or something and as a result, higher rates just don't work most of the time during replays. This is the only example I can find at the moment.
- The final WifePercent in a file may deviate from what it should be, but only by essentially 1 miss. This appears to be a rare bug possibly related to seeking. 
- Seeking in files causes a deviation in the wifescore based on the number of nontaps in the file. Particularly, seeking through files with many holds and mines even if they are dropped or not will cause this.

The expectation is that Replays work fine when watching from start to finish without seeking or pausing. So far that seems to hold true.

**Comment by poco0317** [comment]
Anyways all that's left for Replays is:

- [ ] Restrict changing rates in a way so that Eval doesn't end up with wild numbers
- [ ] Verify that clicking the buttons doesn't click them 3 times (???)
- [ ] Handle setting mods temporarily for Replays; change mods back to what they were before entering Replay
- [ ] Secret feature
- [ ] Add a way to view the Replay from the Eval screen by clicking the graph (make this a choice screen to choose between practice probably)

**Comment by Kangaroux** [comment]
@poco0317 for that third point, does that mean when you view a replay it uses the same mods as it was played with? Same scroll speed, perspective, mirror, hidden, etc.?

**Comment by poco0317** [comment]
Yes. Mirror is actually already considered ever since one of the initial replay implementations. However, I would like to allow matching all mods except noteskin. The reason I didn't in the past is because of the complicated nature of exiting Gameplay/Evaluation in multiple ways. I'm more willing now to force it to work.

At the moment, only rate and mirror is recognized. 

Complications arise when trying to consider additive, random, or removing mods. As long as the mods work consistently, it should be fine.

**Comment by Kangaroux** [comment]
My only concern is if you exit the game mid replay, will it overwrite your mods with the one from the replay?

**Comment by poco0317** [comment]
Yeah the point of being thorough is to make sure that exactly what you said doesn't happen.

I'm taking some necessary steps which should make it clearer whether the player is backing out of gameplay (service switch or otherwise), quitting/ending to eval, restarting gameplay, or any other state I might have left out. From there, handling the cases should be simple. This may end up requiring introduction of a new ScreenEvaluationReplay. My expectation is not having to do that.

**Comment by Kangaroux** [comment]
Instead of trying to cover every use case (which will ultimately fail if you kill the process since you can't react to that), can you leave the player's mods untouched and instead change what mods the game looks at when entering a song?

**Comment by poco0317** [comment]
Killing the process does not save the player mods, so it wouldn't matter. Mods save with the XML, which typically only saves when exiting Evaluation.

It is possible to change just the gameplay mods.

**Comment by poco0317** [comment]
As of writing, Replays are capable of generating their own LifeGraph and ComboGraph. They also apply any mods used during the original score. This specifically can be toggled off in Advanced Options.

Needs testing with mirror and permamirror.

**Comment by poco0317** [comment]
As of writing, combo and life graph recalculation should be a bit more bug free. Still not perfect. 
Scores that use mods which make it difficult to calculate misses (anything that isn't mirror or like nomines) will not generate a graph. Also, CCon scores will not recalculate a graph. This is on purpose.

Starting to fix other tiny bugs and make enhancements now.
Moving on to Practice very soon.

**Comment by poco0317** [comment]
Worked a bit on Practice instead of finishing the cool replay stuff. As of writing, Practice Mode now has a working loop region instead of strict bookmark. Setting the loop region can be done by either pressing Insert Coin to mark the current position, right clicking 2 spots on the graph, or control left clicking 2 spots on the graph. Precise marking can be done by right clicking outside the graph to pause and using the scroll wheel to go through the song at your own leisure, then press Insert Coin to mark the current position.

Loop regions are set by waiting for a first position. If a single position is given, it acts like a bookmark: You can press backspace to jump to it and play until the file ends. Rinse and repeat. If a second position is given using any method, the loop region is created from those 2 end points. Notedata is now restricted to this space only, and the song will loop endlessly in that region (as well as grant a 2 second intro and a 5 second outro so you can see your score). Stats reset every loop and every time you seek. You can press Backspace at any time to immediately jump to either your bookmark (shown as a blue line) or to jump to the start of the loop region (shown as a purple box).

Reset the loop region to bookmark-only form by double right clicking the graph, double ctrl clicking the graph, or double tapping Insert Coin.

I plan on allowing exiting to evaluation soon. Every seeking desync issue specific to practice mode should now be eliminated.

**Comment by Kangaroux** [comment]
@poco0317 I noticed an issue in practice mode where even though the judgement counts would reset, it would seem the total note count used to calculate the % wouldn't reset. Was that also fixed?

Also thank you for the looping that is going to be a big help

**Comment by poco0317** [comment]
All stats truly means all stats. A couple of commits have now been pushed which should make sure the visual side of things updates properly to reflect the reset stats.

**Comment by poco0317** [comment]
Calling this effectively done and ready for a release.
Did not finish #582 #593 #599
Will handle later during development.

**Pull request merged**
