### PR TITLE
Ver0.71.1 Chinese translation for TilDeath, _fallback, and Rebirth

### PR DESCRIPTION
**Pull request by SharpnelXu**
Tested with newest 0.71.1 executable

### CODE REVIEW

**Comment by poco0317** [comment]
Wasnt expecting this so quickly. I planned on adding full translation support to Rebirth at some point and I guess it needs to be done now. Some strings are a little non-trivial to have translated for now

**Comment by SharpnelXu** [comment]
> Wasnt expecting this so quickly. I planned on adding full translation support to Rebirth at some point and I guess it needs to be done now. Some strings are a little non-trivial to have translated for now

In this case I can hold back from translating Rebirth. I don't use Rebirth so I don't have a good idea of what everything is doing.

**Comment by poco0317** [comment]
ok this literally took forever for me to get to but I've finished translation support for Rebirth on the latest develop as of now. go ahead and redo/rebase this PR on that if you want

**Comment by SharpnelXu** [comment]
Finally get back to this, not sure I if did this correctly tbh

**Comment by poco0317** [comment]
after switching the target branch to develop, its looking good. i can tell it isnt finished, but it would work in its current state

**Comment by poco0317** [comment]
gonna merge this so we can have a good point to pick up and continue these changes from

**Pull request merged**
