### PR TITLE
Various tiny fixes and improvements (see within)

### PR DESCRIPTION
**Pull request by poco0317**
- SSM Lua had some updates that run too often so this helps that.
- SSM Lua involving Tags updated twice as often as it should so now it doesn't.
- Added the profiler to ms in sundries.
- Fix the game start bug by removing the ability for it to happen, and also hid some other stuff we don't use.
- Added GetTrueRotationZ for all Actors which we can use for button isOver later regardless of rotation.
- Removed the top 4 things from the key config because it confuses people
- Fix a Lua error that happens when you turn off Judgment text in Gameplay

### CODE REVIEW

**Comment by nico-abram** [comment]
Seems good :+1:

**Comment by poco0317** [comment]
Not ready for merge until it is confirmed that these changes do not break the multiplayer ready button functionality.
To reproduce: Go into Multi on this build. Press Ready. Have anyone else in the lobby press ready or pick a song. The color of the button may change to the wrong status.

**Comment by poco0317** [comment]
Fixed button issue.
Undid sync overlay change because this is handled by the gameplay rewrite.

**Comment by nico-abram** [comment]
This is blocked on https://github.com/etternagame/etterna/pull/597 to avoid conflicts on it

**Pull request merged**
