### PR TITLE
SDG and SDP account for worse judgements

### PR DESCRIPTION
**Pull request by Kotooka**
Hi, sorry for the rather pedantic issue, but it seems like Til Death will rank clears as SDP/SDG even if the number of perfects/greats and all worse judgements total more than 9. This seems less consistent than taking the worse judgements into account since a worse judgement is not better than a perfect/great in terms of accuracy.

### CODE REVIEW

**Comment by poco0317** [comment]
This was done by me already in befd19d94d85c1705429952289e4d4b94b7d9c03 and reverted by mina in 3524b90fa6a9e23ff9a04d670488a202ee5827ed

So I will hold this until feedback from mina himself.

**Comment by Kotooka** [comment]
Yeah I heard about that on Discord lol. https://github.com/etternagame/etterna/commit/befd19d94d85c1705429952289e4d4b94b7d9c03 matches what other games (supposedly) do by only showing SDP/SDG if it's already a FC. This change treats greats and misses as perfects when computing SDP and misses as greats when computing SDG without checking for FC.

**Comment by g-robertson** [comment]
If you do end up making a change like this I would suggest just making it take the worst grade available instead of keeping the same structure for the code
Example in the pseudocode below
```
if grade == "Grade_Failed":
  clearlevel = 11 // Failed
elif missCount > 9:
  clearlevel = 10 // Clear
elif missCount > 1:
  clearlevel = 9 // SDCB
elif missCount == 1:
  clearlevel = 8 // MF
elif greatCount > 9:
  clearlevel = 7 // FC
elif greatCount > 1:
  clearlevel = 6 // SDG
elif greatCount == 1:
  clearlevel = 5 // BF
elif perfectCount > 9:
  clearlevel = 4 // PFC
elif perfectCount > 1:
  clearlevel = 3 // SDP
elif perfectCount == 1:
  clearlevel = 2 // WF
else:
  clearlevel = 1 // MFC
```

**Comment by Kotooka** [comment]
I believe that's what https://github.com/etternagame/etterna/commit/befd19d94d85c1705429952289e4d4b94b7d9c03 was trying to accomplish because it made FC a prereq for SDG.

I got this with Til Death yesterday, and it just seems weird since it just ignores the CBs. (I'm not good at this game lol.)
seems_wrong
In https://github.com/etternagame/etterna/commit/befd19d94d85c1705429952289e4d4b94b7d9c03 and this MR this would be a SDCB. If this was 0 greats though, https://github.com/etternagame/etterna/commit/befd19d94d85c1705429952289e4d4b94b7d9c03 would evaluate it as a SDCB still while this MR would treat it as a SDG. In the same vein, this MR would treat a score with all marvelous with 1 green/CB as SDP.

I'm under the assumption that the intent is to not punish too harshly for CBs (at least from what I heard about the move to Wife3), and this seems like a decent compromise. I wouldn't mind just doing https://github.com/etternagame/etterna/commit/befd19d94d85c1705429952289e4d4b94b7d9c03 since it just feels like the current thing is weird but 🤷‍♂️

**Comment by MinaciousGrace** [comment]
ok i could spend all day nitpicking about this topic but i'm not really invested enough anymore and never really considered clear types a primary means of communicating information in the first place

so i'm not going to do anything but preemptively sign off on whatever changes you guys end up with

**Comment by poco0317** [comment]
a12a82573bf10ddcdcf26aa1eaae24763a9a7263
1fd615cc5f6024b1da12a559c5e511d3be752d22

**Pull request closed without merging**
